#!/usr/bin/env sh
set -ex

rm -rf scratch
mkdir scratch
mkdir scratch/install scratch/bin

zigup="./zig-cache/bin/zigup --install-dir scratch/install --path-link scratch/bin/zig"

$zigup -h 2>&1 | grep Usage
$zigup --help 2>&1 | grep Usage
$zigup $opt || true
$zigup default
$zigup fetch-index
$zigup 0.5.0
$zigup fetch 0.5.0
$zigup master
$zigup list
$zigup default 0.5.0
$zigup default master
touch scratch/install/0.5.0/keep
touch scratch/install/master/keep
$zigup clean # should do nothing because we keep master and 0.5.0
rm scratch/install/0.5.0/keep
$zigup clean # deletes 0.5.0
$zigup master
