#!/usr/bin/env sh
set -ex

testCompilerCount() {
  compiler_count=$(find scratch/install -mindepth 1 -maxdepth 1 -type d | wc -l)
  test "$compiler_count" = $1
}

rm -rf scratch
mkdir scratch
mkdir scratch/install scratch/bin

zigup="./zig-cache/bin/zigup --install-dir scratch/install --path-link scratch/bin/zig"

$zigup -h 2>&1 | grep Usage
$zigup --help 2>&1 | grep Usage
$zigup $opt || true
$zigup default
$zigup fetch-index
$zigup 0.5.0
$zigup fetch 0.5.0
$zigup master
$zigup 0.6.0
$zigup list
$zigup default 0.5.0

testCompilerCount 3

touch scratch/install/0.6.0/keep
$zigup clean # doesn't delete anything because we have keepfile and master doens't get deleted
testCompilerCount 3

rm scratch/install/0.6.0/keep
$zigup clean 2>&1 | grep "because it is master" # DOESN't delete master because we dont delete master, but DOES delete 0.6.0
testCompilerCount 2

$zigup master
testCompilerCount 2

$zigup DOESNOTEXIST 2>&1 | grep "HTTP request failed"
testCompilerCount 2

echo Success
